### ISSUE TITLE
A guide to create this app from scratch(request rather than issue) 

### ISSUE THREAD

**Issue by jasan-s** [paulhoughton/remember#1]
First of all @paulhoughton beautiful app. I have been using it quite a bit recently. I am quite excited about the potential of PWA and wanted to create a React+Redux PWA app myself. If possible would you consider writing a high level guide to recreating the remember app from scratch.

**Comment by paulhoughton** [comment]
Thanks but I'm not sure how much I can add to the existing guides? I can certainly put together a starter kit based on this application which should help get you going?

**Comment by paulhoughton** [comment]
I've extracted the core functionality here - [React PWA](https://github.com/paulhoughton/react-pwa/)

Hopefully it should provide a simple way to get started with similar applications.
