### ISSUE TITLE
orientation data differs from ios and android. 

### ISSUE THREAD

**Issue by jasan-s** [paulhoughton/remember#2]
did you ever figure out how to handle the different orientation data from ios since ios  does not just work with alpha value. ?  and can you elaborate the following calculation:   const `orient = Math.floor(360 - (720 - (geo.orientation || 0) - deg) % 360);`

**Comment by paulhoughton** [comment]
Sorry, I don't have an ios device to confirm on.

orient calculation just ensures value is always between 0 and 360
